# Spørg brugeren om opdatering af download-listen
$choice = Read-Host "Update Download-List from GitHub? (Type 'github' to update or press Enter to use current)"

if ($choice -eq "github") {
    # Definer GitHub URL
    $githubUrl = "https://raw.githubusercontent.com/Henrik-Bruun/PowerShell-AutoUpdaterFunctions/main/Download-List.txt"

    # Hent indholdet fra GitHub
    $downloadListContent = Invoke-RestMethod -Uri $githubUrl

    # Gem indholdet i Download-List.txt
    $downloadListContent | Out-File -FilePath ".\Download-List.txt" -Encoding UTF8

    # Gem indholdet i [YYmmDD HH:MM]-Download-List.txt
    $timestamp = Get-Date -Format "yyMMdd HHmm"
    $downloadListContent | Out-File -FilePath ".\$timestamp-Download-List.txt" -Encoding UTF8

    Write-Host "Download-List updated successfully and saved in Download-List.txt and $timestamp-Download-List.txt"
} else {
    Write-Host "Using current Download-List."
}

# Read Download-List content
$downloadListContent = Get-Content .\Download-List.txt
# Header for Henrik-Bruun.psm1
$header = @"
<#
# This is generated by an auto-update $((Get-Date).ToString("yyyy MMMM dd"))
This will download all my Public PowerShell functions. You can import them with
    Import-Module .\Henrik-Bruun.psm1

or only import sub part of modules 
- example.
    Import-Module .\Convert-MAC.psm1
    Import-Module .\Get-MACvendor.psm1


https://github.com/Henrik-Bruun
        Author: Henrik Bruun  Github.com @Henrik-Bruun
        Version: 1.0 2023 december
#>
"@
$header | Out-File -FilePath ".\Henrik-Bruun.psm1" -Encoding UTF8


Write-Host "Modules"
Write-Host ""
foreach ($line in $downloadListContent) {
    if ($line.Length -gt 10){
    # Extract the filename from the URL
    $filename = [System.IO.Path]::GetFileName($line)

    # Download content from the URL
    $content = Invoke-RestMethod -Uri $line

    # Save content with the extracted filename
    $content | Out-File -FilePath ".\$filename" -Encoding UTF8
    
    Write-Host "$filename"
    # Append content to Henrik-Bruun.psm1
    $content | Add-Content -Path ".\Henrik-Bruun.psm1" -Encoding UTF8
}
}
Write-Host ""
Write-Host "Downloaded content saved with individual filenames and appended to Henrik-Bruun.psm1"
